export const CATEGORY_CREATE_BEGIN = "CATEGORY_CREATE_BEGIN";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";
export const CATEGORY_CREATE_RESET = "CATEGORY_CREATE_RESET";

export const CATEGORY_EDIT_BEGIN = "CATEGORY_EDIT_BEGIN";
export const CATEGORY_EDIT_SUCCESS = "CATEGORY_EDIT_SUCCESS";
export const CATEGORY_EDIT_FAIL = "CATEGORY_EDIT_FAIL";
export const CATEGORY_EDIT_RESET = "CATEGORY_EDIT_RESET";
