export const USER_DETAIL_BEGIN = "USER_DETAIL_BEGIN";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";

export const UPDATEUSER_DETAIL_BEGIN = "UPDATEUSER_DETAIL_BEGIN";
export const UPDATEUSER_DETAIL_SUCCESS = "UPDATEUSER_DETAIL_SUCCESS";
export const UPDATEUSER_DETAIL_FAIL = "UPDATEUSER_DETAIL_FAIL";

export const USER_DETAIL_RESET = "USER_DETAIL_RESET";
